package de.ibmix.magkit.ui.rendering;

/*-
 * #%L
 * IBM iX Magnolia Kit
 * %%
 * Copyright (C) 2023 IBM iX
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

import info.magnolia.jcr.util.NodeUtil;
import info.magnolia.jcr.util.PropertyUtil;
import info.magnolia.rendering.engine.RenderException;
import info.magnolia.rendering.generator.CopyGenerator;
import info.magnolia.rendering.template.AutoGenerationConfiguration;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.jcr.Node;
import javax.jcr.RepositoryException;

/**
 * CopyGenerator variant that ensures a given parent's auto-generation runs only once.
 * <p>Purpose: Prevent duplicate creation of auto-generated child content (e.g. areas/components) by marking
 * the parent node with a boolean flag after the first successful generation.</p>
 * <p>Main features:</p>
 * <ul>
 *     <li>Delegates to Magnolia's {@link CopyGenerator} for actual generation logic.</li>
 *     <li>Uses a marker property {@code isAutogenerated} on the parent node to guard repeated execution.</li>
 *     <li>Persists the marker and session immediately after first run.</li>
 * </ul>
 *
 * <p>Usage preconditions: Provide a non-null parent {@link Node} with write access; the session must allow saving.
 * If repository permissions deny setting properties or saving, generation will still occur but the guard flag may not be stored.</p>
 * <p>Side effects: Sets JCR property {@code isAutogenerated=true} and saves the parent node's session.</p>
 * <p>Null and error handling: Exceptions while persisting the marker are logged; the method does not rethrow them.
 * Rendering exceptions from the delegated super implementation propagate.</p>
 * <p>Thread-safety: Instances are not thread-safe; they keep a reference to a mutable JCR {@link Node}. Use per rendering operation.</p>
 * <p>Usage example:</p>
 * <pre>{@code
 * Node area = ... // obtain area node
 * AutoGenerationConfiguration&lt;?&gt; cfg = ... // Magnolia configuration
 * new OnlyOnceCopyGenerator(area).generate(cfg);
 * }</pre>
 *
 *
 * @author wolf.bubenik@ibmix.de
 * @since 2019-08-14
 */
public class OnlyOnceCopyGenerator extends CopyGenerator {

    private static final String PN_AUTOGENERATED = "isAutogenerated";
    private static final Logger LOG = LoggerFactory.getLogger(OnlyOnceCopyGenerator.class);

    private final Node _parent;

    /**
     * Create a generator bound to a parent node that will be marked after first generation.
     *
     * @param parent the parent node that receives the auto-generated content and the guarding marker property; must not be null
     */
    public OnlyOnceCopyGenerator(final Node parent) {
        super(parent);
        _parent = parent;
    }

    /**
     * Execute auto-generation only if the marker property {@code isAutogenerated} is not yet set.
     * Delegates to {@link CopyGenerator#generate(AutoGenerationConfiguration)} and then stores the marker flag.
     *
     * @param autoGenerationConfig Magnolia auto-generation configuration providing source content definitions
     * @throws RenderException if underlying rendering/generation fails
     */
    @Override
    public void generate(AutoGenerationConfiguration autoGenerationConfig) throws RenderException {
        if (!PropertyUtil.getBoolean(_parent, PN_AUTOGENERATED, false)) {
            super.generate(autoGenerationConfig);
            try {
                PropertyUtil.setProperty(_parent, PN_AUTOGENERATED, true);
                _parent.getSession().save();
            } catch (RepositoryException e) {
                LOG.error("Failed to set property 'isAutogenerated' to Node " + NodeUtil.getPathIfPossible(_parent), e);
            }
        }
    }
}
