package com.aperto.magkit.rendering;

import info.magnolia.jcr.util.NodeUtil;
import info.magnolia.jcr.util.PropertyUtil;
import info.magnolia.rendering.engine.RenderException;
import info.magnolia.rendering.generator.CopyGenerator;
import info.magnolia.rendering.template.AutoGenerationConfiguration;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.jcr.Node;
import javax.jcr.RepositoryException;

public class OnlyOnceCopyGenerator extends CopyGenerator {

    private static final String PN_AUTOGENERATED = "isAutogenerated";
    private static final Logger LOG = LoggerFactory.getLogger(OnlyOnceCopyGenerator.class);

    private Node _parent;

    public OnlyOnceCopyGenerator(final Node parent) {
        super(parent);
        _parent = parent;
    }

    @Override
    public void generate(AutoGenerationConfiguration autoGenerationConfig) throws RenderException {
        if (!PropertyUtil.getBoolean(_parent, PN_AUTOGENERATED, false)) {
            super.generate(autoGenerationConfig);
            try {
                PropertyUtil.setProperty(_parent, PN_AUTOGENERATED, true);
                _parent.getSession().save();
            } catch (RepositoryException e) {
                LOG.error("Failed to set property 'isAutogenerated' to Node " + NodeUtil.getPathIfPossible(_parent), e);
            }
        }
    }
}
