package de.ibmix.magkit.ui.rendering;

/*-
 * #%L
 * IBM iX Magnolia Kit
 * %%
 * Copyright (C) 2023 IBM iX
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

import info.magnolia.rendering.engine.RenderException;
import info.magnolia.rendering.template.AutoGenerationConfiguration;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import javax.jcr.Node;
import javax.jcr.RepositoryException;
import java.util.HashMap;
import java.util.Map;

import static de.ibmix.magkit.test.cms.context.ContextMockUtils.cleanContext;
import static de.ibmix.magkit.test.cms.node.MagnoliaNodeMockUtils.mockAreaNode;
import static de.ibmix.magkit.test.jcr.NodeStubbingOperation.stubProperty;
import static org.mockito.Mockito.doReturn;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;

/**
 * Tests for {@link OnlyOnceCopyGenerator}.
 *
 * @author wolf.bubenik@ibmix.de
 * @since 2023-06-02
 */
public class OnlyOnceCopyGeneratorTest {

    private Node _area;
    private AutoGenerationConfiguration<Map<String, Object>> _config;

    private OnlyOnceCopyGenerator _generator;

    @Before
    public void setUp() throws Exception {
        _area = mockAreaNode("stageArea");
        _config = mock(AutoGenerationConfiguration.class);
        _generator = new OnlyOnceCopyGenerator(_area);
    }

    @Test
    public void generate() throws RepositoryException, RenderException {
        // Mock area that has no autogenerated content:
        Map<String, Object> content = new HashMap<>();
        doReturn(content).when(_config).getContent();

        _generator.generate(_config);
        // verify checking area marker property:
        verify(_area, times(2)).hasProperty("isAutogenerated");
        // verify executing autogeneration (reading config)
        verify(_config, times(1)).getContent();
        // verify setting marker property:
        verify(_area, times(1)).setProperty("isAutogenerated", true);
        // verify saving session:
        verify(_area.getSession(), times(1)).save();
    }

    @Test
    public void generateNot() throws RepositoryException, RenderException {
        // Mock area that has autogenerated content:
        stubProperty("isAutogenerated", true).of(_area);

        _generator.generate(_config);
        // verify checking area marker property:
        verify(_area, times(1)).hasProperty("isAutogenerated");
        // verify NOT executing autogeneration (reading config)
        verify(_config, never()).getContent();
        // verify NOT setting marker property again:
        verify(_area, never()).setProperty("isAutogenerated", true);
        // verify NOT saving session:
        verify(_area.getSession(), never()).save();
    }

    @After
    public void tearDown() throws Exception {
        cleanContext();
    }
}
